//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.LangResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.LangResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abbreviation.
        /// </summary>
        internal static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Owner.
        /// </summary>
        internal static string AccountOwner {
            get {
                return ResourceManager.GetString("AccountOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accounts.
        /// </summary>
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add customer type.
        /// </summary>
        internal static string AddCustomerType {
            get {
                return ResourceManager.GetString("AddCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Addresses.
        /// </summary>
        internal static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Commercial Assistant.
        /// </summary>
        internal static string Assistant {
            get {
                return ResourceManager.GetString("Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Associated products.
        /// </summary>
        internal static string Associated_Products {
            get {
                return ResourceManager.GetString("Associated_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attach file.
        /// </summary>
        internal static string AttachFile {
            get {
                return ResourceManager.GetString("AttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available Stock.
        /// </summary>
        internal static string Available_Stock {
            get {
                return ResourceManager.GetString("Available_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balance AR$.
        /// </summary>
        internal static string BalanceArg {
            get {
                return ResourceManager.GetString("BalanceArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balance units.
        /// </summary>
        internal static string BalanceUnits {
            get {
                return ResourceManager.GetString("BalanceUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balance US$.
        /// </summary>
        internal static string BalanceUS {
            get {
                return ResourceManager.GetString("BalanceUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Branch Office.
        /// </summary>
        internal static string BranchOffice {
            get {
                return ResourceManager.GetString("BranchOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reg. Name.
        /// </summary>
        internal static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Opportunity.
        /// </summary>
        internal static string CloseOpportunity {
            get {
                return ResourceManager.GetString("CloseOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        internal static string CloseSession {
            get {
                return ResourceManager.GetString("CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corporate Customer.
        /// </summary>
        internal static string CorporateCustomer {
            get {
                return ResourceManager.GetString("CorporateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Customer.
        /// </summary>
        internal static string CreateCustomer {
            get {
                return ResourceManager.GetString("CreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current account.
        /// </summary>
        internal static string CurrentAccount {
            get {
                return ResourceManager.GetString("CurrentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This Customer has got not assigned an Address.
        /// </summary>
        internal static string CustomerAddressAlert {
            get {
                return ResourceManager.GetString("CustomerAddressAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importer.
        /// </summary>
        internal static string CustomerImporter {
            get {
                return ResourceManager.GetString("CustomerImporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customers.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer Type.
        /// </summary>
        internal static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivery Address.
        /// </summary>
        internal static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivery Branch.
        /// </summary>
        internal static string DeliveryBranch {
            get {
                return ResourceManager.GetString("DeliveryBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivery Date.
        /// </summary>
        internal static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivery Resp..
        /// </summary>
        internal static string DeliveryResponsible {
            get {
                return ResourceManager.GetString("DeliveryResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Describe who delivers.
        /// </summary>
        internal static string DescribeWhoDelivers {
            get {
                return ResourceManager.GetString("DescribeWhoDelivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter description.
        /// </summary>
        internal static string Description_PL {
            get {
                return ResourceManager.GetString("Description_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Off.
        /// </summary>
        internal static string DiscountPopUp {
            get {
                return ResourceManager.GetString("DiscountPopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End Date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End Price.
        /// </summary>
        internal static string EndPrice {
            get {
                return ResourceManager.GetString("EndPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LogIn.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter abbreviation.
        /// </summary>
        internal static string EnterAbbreviation {
            get {
                return ResourceManager.GetString("EnterAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter company name.
        /// </summary>
        internal static string EnterCompanyName {
            get {
                return ResourceManager.GetString("EnterCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Customer.
        /// </summary>
        internal static string EnterCustomer {
            get {
                return ResourceManager.GetString("EnterCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Description.
        /// </summary>
        internal static string EnterDescription {
            get {
                return ResourceManager.GetString("EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Email.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter id numer.
        /// </summary>
        internal static string EnterIdNumer {
            get {
                return ResourceManager.GetString("EnterIdNumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter reg. name.
        /// </summary>
        internal static string EnterRegName {
            get {
                return ResourceManager.GetString("EnterRegName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error .
        /// </summary>
        internal static string ErrorLoginMsg {
            get {
                return ResourceManager.GetString("ErrorLoginMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimated Time of Delivery.
        /// </summary>
        internal static string EstimatedTimeDelivery {
            get {
                return ResourceManager.GetString("EstimatedTimeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Files.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter Opportunity.
        /// </summary>
        internal static string Filter_Opportunity {
            get {
                return ResourceManager.GetString("Filter_Opportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter By.
        /// </summary>
        internal static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MM/dd/yyyy.
        /// </summary>
        internal static string FormatDate {
            get {
                return ResourceManager.GetString("FormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Freight.
        /// </summary>
        internal static string Freight {
            get {
                return ResourceManager.GetString("Freight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Freight in Charge.
        /// </summary>
        internal static string FreightCharge {
            get {
                return ResourceManager.GetString("FreightCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From Date.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From Price.
        /// </summary>
        internal static string FromPrice {
            get {
                return ResourceManager.GetString("FromPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate proposal.
        /// </summary>
        internal static string Generate_proposal {
            get {
                return ResourceManager.GetString("Generate_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Number.
        /// </summary>
        internal static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Type.
        /// </summary>
        internal static string IdType {
            get {
                return ResourceManager.GetString("IdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must first register the opportunity to be able to close it.
        /// </summary>
        internal static string InfoTextCloseOpportunity {
            get {
                return ResourceManager.GetString("InfoTextCloseOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        internal static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Final Client.
        /// </summary>
        internal static string IsFinalClient {
            get {
                return ResourceManager.GetString("IsFinalClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logging in....
        /// </summary>
        internal static string Loggin {
            get {
                return ResourceManager.GetString("Loggin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid username or password..
        /// </summary>
        internal static string LoginInvalidMsg {
            get {
                return ResourceManager.GetString("LoginInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lost.
        /// </summary>
        internal static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Order.
        /// </summary>
        internal static string NewOrder {
            get {
                return ResourceManager.GetString("NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no associated products.
        /// </summary>
        internal static string No_Associated_Products {
            get {
                return ResourceManager.GetString("No_Associated_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N of OC Customer.
        /// </summary>
        internal static string NOCCustomer {
            get {
                return ResourceManager.GetString("NOCCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No contacts.
        /// </summary>
        internal static string NoContacts {
            get {
                return ResourceManager.GetString("NoContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No customers found.
        /// </summary>
        internal static string NoCustomersFound {
            get {
                return ResourceManager.GetString("NoCustomersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No directions.
        /// </summary>
        internal static string NoDirections {
            get {
                return ResourceManager.GetString("NoDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If the Opportunity is closed is not possible edit it.
        /// </summary>
        internal static string NoEditOpportunity {
            get {
                return ResourceManager.GetString("NoEditOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No opportunities found.
        /// </summary>
        internal static string NoOpportunitiesFound {
            get {
                return ResourceManager.GetString("NoOpportunitiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Orders Found.
        /// </summary>
        internal static string NoOrdersFound {
            get {
                return ResourceManager.GetString("NoOrdersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Products found.
        /// </summary>
        internal static string NoProductsFound {
            get {
                return ResourceManager.GetString("NoProductsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OC Customer.
        /// </summary>
        internal static string OCCustomer {
            get {
                return ResourceManager.GetString("OCCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opportunities.
        /// </summary>
        internal static string Opportunities {
            get {
                return ResourceManager.GetString("Opportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opportunities per State.
        /// </summary>
        internal static string OpportunitiesPerState {
            get {
                return ResourceManager.GetString("OpportunitiesPerState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opportunity.
        /// </summary>
        internal static string Opportunity {
            get {
                return ResourceManager.GetString("Opportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orders.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Condition.
        /// </summary>
        internal static string PaymentCondition {
            get {
                return ResourceManager.GetString("PaymentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Method.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place Payment.
        /// </summary>
        internal static string PlacePayment {
            get {
                return ResourceManager.GetString("PlacePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price List.
        /// </summary>
        internal static string PriceList {
            get {
                return ResourceManager.GetString("PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover Password.
        /// </summary>
        internal static string RecoverPass {
            get {
                return ResourceManager.GetString("RecoverPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You will receive an email with the instructions to recover your password.
        /// </summary>
        internal static string RecoverPassInfo {
            get {
                return ResourceManager.GetString("RecoverPassInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registered.
        /// </summary>
        internal static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remittance Type.
        /// </summary>
        internal static string RemittanceType {
            get {
                return ResourceManager.GetString("RemittanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset filters.
        /// </summary>
        internal static string ResetFilters {
            get {
                return ResourceManager.GetString("ResetFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sales.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Customer.
        /// </summary>
        internal static string SearchCustomer {
            get {
                return ResourceManager.GetString("SearchCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Opportunity.
        /// </summary>
        internal static string SearchOpportunity {
            get {
                return ResourceManager.GetString("SearchOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Addres.
        /// </summary>
        internal static string SelectAddressTitle {
            get {
                return ResourceManager.GetString("SelectAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a Company.
        /// </summary>
        internal static string SelectCompany {
            get {
                return ResourceManager.GetString("SelectCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a condition.
        /// </summary>
        internal static string SelectCondition {
            get {
                return ResourceManager.GetString("SelectCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a corporate company.
        /// </summary>
        internal static string SelectCorporateCompany {
            get {
                return ResourceManager.GetString("SelectCorporateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select type of Id.
        /// </summary>
        internal static string SelectTypeId {
            get {
                return ResourceManager.GetString("SelectTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a user.
        /// </summary>
        internal static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seller.
        /// </summary>
        internal static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Since.
        /// </summary>
        internal static string Since {
            get {
                return ResourceManager.GetString("Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TaxCondition.
        /// </summary>
        internal static string TaxCondition {
            get {
                return ResourceManager.GetString("TaxCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Amount.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Until.
        /// </summary>
        internal static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Company.
        /// </summary>
        internal static string UserCompany {
            get {
                return ResourceManager.GetString("UserCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To close the opportunity, the client must be registered in the external service..
        /// </summary>
        internal static string WithoutExternId {
            get {
                return ResourceManager.GetString("WithoutExternId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Won.
        /// </summary>
        internal static string Won {
            get {
                return ResourceManager.GetString("Won", resourceCulture);
            }
        }
    }
}
